HAI 1.4

CAN HAS STDLIB?

I HAS A DECK ITZ A BUKKIT

BTW RANKS 
I HAS A RANKS ITZ A BUKKIT
RANKS HAS A SRS 0 ITZ "A"
RANKS HAS A SRS 1 ITZ "2"
RANKS HAS A SRS 2 ITZ "3"
RANKS HAS A SRS 3 ITZ "4"
RANKS HAS A SRS 4 ITZ "5"
RANKS HAS A SRS 5 ITZ "6"
RANKS HAS A SRS 6 ITZ "7"
RANKS HAS A SRS 7 ITZ "8"
RANKS HAS A SRS 8 ITZ "9"
RANKS HAS A SRS 9 ITZ "10"
RANKS HAS A SRS 10 ITZ "J"
RANKS HAS A SRS 11 ITZ "Q"
RANKS HAS A SRS 12 ITZ "K"

BTW SUITS
I HAS A SUITS ITZ A BUKKIT
SUITS HAS A SRS 0 ITZ "Spades"
SUITS HAS A SRS 1 ITZ "Hearts"
SUITS HAS A SRS 2 ITZ "Clubs"
SUITS HAS A SRS 3 ITZ "Diamonds"

I HAS A PLAYER_POINTS ITZ 100
I HAS A CHOICE
I HAS A HIT_STAND
I HAS A RAN_NUM ITZ 0

RAN_NUM R SUM OF RAN_NUM AN 1
VISIBLE RAN_NUM

HOW IZ I START
    VISIBLE "HAI!! WELCOME TO BLACKJACK!!!"
    VISIBLE "THE DEALER DOES NOT HIT ON A SOFT 17"
    VISIBLE "POINTS : 100"
    VISIBLE "DO YOU WANT TO PLAY? (Y/N)"

    GIMMEH CHOICE

    BOTH SAEM CHOICE AN "Y"
    O RLY?
        YA RLY
            VISIBLE "LETS PLAY"
            I IZ FIRSTHAND MKAY
        NO WAI
            VISIBLE "BYE BYE"
    OIC
IF U SAY SO


HOW IZ I FIRSTHAND  
    VISIBLE "YOUR FIRST CARD IS : " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
    VISIBLE "YOUR SECOND CARD IS : " RANKS'Z SRS 2 " OF " SUITS'Z SRS 0
    VISIBLE "THE DEALERS FIRST CARD IS : 8 OF CLUBS"
    VISIBLE "THE DEALERS SECOND CARD IS HIDDEN"
    VISIBLE "DO YOU WANT TO HIT OR STAND? (H/S)"
    GIMMEH HIT_STAND
    BOTH SAEM HIT_STAND AN "H"
    O RLY?
        YA RLY
            I IZ MANYHANDS MKAY
        NO WAI 
            VISIBLE "YOUR POINTS : 5"
            VISIBLE "THE DEALERS HIDDEN CARD WAS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
            VISIBLE "THE DEALERS POINTS WAS " SUM OF RAN_NUM AN 9
    OIC
IF U SAY SO


HOW IZ I MANYHANDS
    RAN_NUM R SUM OF RAN_NUM AN 1
    VISIBLE "YOUR CARD IS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
    VISIBLE "DO YOU WANT TO HIT OR STAND (H/S)"
    GIMMEH HIT_STAND 
    BOTH SAEM HIT_STAND AN "H"
    O RLY?
        YA RLY 
            I IZ FIRSTHAND MKAY
        NO WAI
            I IZ START MKAY
    OIC
IF U SAY SO

I IZ START MKAY

KTHXBYE