HAI 1.4

CAN HAS STDLIB?

I HAS A DECK ITZ A BUKKIT

BTW RANKS 
I HAS A RANKS ITZ A BUKKIT
RANKS HAS A SRS 0 ITZ ""
RANKS HAS A SRS 1 ITZ "A"
RANKS HAS A SRS 2 ITZ "2"
RANKS HAS A SRS 3 ITZ "3"
RANKS HAS A SRS 4 ITZ "4"
RANKS HAS A SRS 5 ITZ "5"
RANKS HAS A SRS 6 ITZ "6"
RANKS HAS A SRS 7 ITZ "7"
RANKS HAS A SRS 8 ITZ "8"
RANKS HAS A SRS 9 ITZ "9"
RANKS HAS A SRS 10 ITZ "10"
RANKS HAS A SRS 11 ITZ "J"
RANKS HAS A SRS 12 ITZ "Q"
RANKS HAS A SRS 13 ITZ "K"

BTW SUITS
I HAS A SUITS ITZ A BUKKIT
SUITS HAS A SRS 0 ITZ ""
SUITS HAS A SRS 1 ITZ "Spades"
SUITS HAS A SRS 2 ITZ "Hearts"
SUITS HAS A SRS 3 ITZ "Clubs"
SUITS HAS A SRS 4 ITZ "Diamonds"
SUITS HAS A SRS 5 ITZ "Spades"
SUITS HAS A SRS 6 ITZ "Hearts"
SUITS HAS A SRS 7 ITZ "Clubs"
SUITS HAS A SRS 8 ITZ "Diamonds"
SUITS HAS A SRS 9 ITZ "Spades"
SUITS HAS A SRS 10 ITZ "Hearts"

I HAS A PLAYER_POINTS ITZ 100
I HAS A PLAYER_CARD_POINTS ITZ 0
I HAS A DEALER_CARD_POINTS ITZ 0
I HAS A CHOICE
I HAS A HIT_STAND
I HAS A RAN_NUM ITZ 1

HOW IZ I START
    VISIBLE "HAI!! WELCOME TO BLACKJACK!!!"
    VISIBLE "THE DEALER DOES NOT HIT ON A SOFT 17"
    VISIBLE "POINTS : " PLAYER_POINTS
    VISIBLE "DO YOU WANT TO PLAY? (Y/N)"

    GIMMEH CHOICE

    BOTH SAEM CHOICE AN "Y"
    O RLY?
        YA RLY
            VISIBLE "LETS PLAY"
            I IZ FIRSTHAND MKAY
        NO WAI
            VISIBLE "BYE BYE"
    OIC
IF U SAY SO


HOW IZ I FIRSTHAND  
    VISIBLE "YOUR FIRST CARD IS : " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
    PLAYER_CARD_POINTS R SUM OF PLAYER_CARD_POINTS AN RAN_NUM
    VISIBLE "YOUR SECOND CARD IS : " RANKS'Z SRS 2 " OF " SUITS'Z SRS 0
    PLAYER_CARD_POINTS R SUM OF RAN_NUM AN 2
    VISIBLE "THE DEALERS FIRST CARD IS : 8 OF CLUBS"
    DEALER_CARD_POINTS R SUM OF DEALER_CARD_POINTS AN 8
    VISIBLE "THE DEALERS SECOND CARD IS HIDDEN"
    VISIBLE "DO YOU WANT TO HIT OR STAND? (H/S)"
    GIMMEH HIT_STAND
    BOTH SAEM HIT_STAND AN "H"
    O RLY?
        YA RLY
            I IZ MANYHANDS MKAY
        NO WAI 
            VISIBLE "YOUR POINTS : " PLAYER_CARD_POINTS
            VISIBLE "THE DEALERS HIDDEN CARD WAS 10 OF DIAMONDS"
            VISIBLE "THE DEALERS POINTS WAS " SUM OF 10 AN 8
            I IZ COMPARE MKAY
    OIC
IF U SAY SO


HOW IZ I MANYHANDS
    I HAS A RAN_NUM ITZ 0
    RAN_NUM R SUM OF RAN_NUM AN 1

    GIMMEH HIT_STAND
    IM IN YR LOOPY
        BOTH SAEM RAN_NUM AN 11
        O RLY?
            YA RLY
            RAN_NUM R 1
        OIC
        VISIBLE "YOUR CARD IS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
        PLAYER_CARD_POINTS R SUM OF PLAYER_CARD_POINTS AN RAN_NUM
        RAN_NUM R SUM OF RAN_NUM AN 1
        VISIBLE "YOUR POINTS ARE " PLAYER_CARD_POINTS

        VISIBLE "DO YOU WANT TO HIT OR STAND (H/S)"
        GIMMEH HIT_STAND

        BOTH SAEM HIT_STAND AN "S", O RLY?
            YA RLY 
                VISIBLE "THE DEALERS HIDDEN CARD IS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
                DEALER_CARD_POINTS R SUM OF DEALER_CARD_POINTS AN RAN_NUM
                IM IN YR DEALERLOOP
                BOTH SAEM DEALER_CARD_POINTS AN SMALLR OF DEALER_CARD_POINTS AN 17  BTW x <= y
                    O RLY?
                        YA RLY
                            RAN_NUM R SUM OF RAN_NUM AN 1
                            DEALER_CARD_POINTS R SUM OF DEALER_CARD_POINTS AN RAN_NUM
                            VISIBLE "THE DEALERS CARD IS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
                        NO WAI
                             GTFO
                    OIC
                IM OUTTA YR DEALERLOOP

                VISIBLE "THE DEALERS HIDDEN CARD IS " RANKS'Z SRS RAN_NUM " OF " SUITS'Z SRS RAN_NUM
                VISIBLE "THE DEALERS POINTS ARE " DEALER_CARD_POINTS
                VISIBLE "YOUR TOTAL CARD POINTS ARE " PLAYER_CARD_POINTS
                I IZ COMPARE MKAY
        OIC
    IM OUTTA YR LOOPY

    VISIBLE "FINAL POINTS: " PLAYER_CARD_POINTS

IF U SAY SO

HOW IZ I COMPARE
    DIFFRINT PLAYER_CARD_POINTS AN SMALLR OF PLAYER_CARD_POINTS AN 21
    O RLY?
        YA RLY
            PLAYER_POINTS R DIFF OF PLAYER_POINTS AN 10
            VISIBLE "YOU WENT OVER 21! YOU LOSE"
            I IZ START MKAY
    OIC
    
    DIFFRINT DEALER_CARD_POINTS AN SMALLR OF DEALER_CARD_POINTS AN 21   BTW x > y
    O RLY?
        YA RLY 
            PLAYER_POINTS R SUM OF PLAYER_POINTS AN 10
            VISIBLE "DEALER WENT OVER! YOU WIN"
            I IZ START MKAY
    OIC

    BOTH SAEM PLAYER_CARD_POINTS AN 21 BTW x == Y
    O RLY?
        YA RLY
            PLAYER_POINTS R SUM OF PLAYER_POINTS AN 15
            VISIBLE "BLACKJACK! YOU WIN!" 
            I IZ START MKAY
    OIC

    DIFFRINT DEALER_CARD_POINTS AN SMALLR OF DEALER_CARD_POINTS AN PLAYER_CARD_POINTS BTW x > y
    O RLY?
        YA RLY
            PLAYER_POINTS R DIFF OF PLAYER_POINTS AN 10
            VISIBLE "YOU LOSE! DEALER WINS."
            I IZ START MKAY
    OIC

    DIFFRINT PLAYER_CARD_POINTS AN SMALLR OF PLAYER_CARD_POINTS AN DEALER_CARD_POINTS   BTW x > y
    O RLY?
        YA RLY 
            PLAYER_POINTS R SUM OF PLAYER_POINTS AN 10
            VISIBLE "YOU WIN!"
            I IZ START MKAY

    OIC

IF U SAY SO

I IZ START MKAY

KTHXBYE