HAI 1.4

CAN HAS STDIO?

HOW IZ I FIRSTHAND
    VISIBLE "YOUR FIRST CARD IS : 2 OF SPADES"    
    VISIBLE "YOUR SECOND CARD IS : 5 OF DIAMONDS"
    VISIBLE "THE DEALERS FIRST CARD IS : 8 OF CLUBS"
    VISIBLE "THE DEALERS SECOND CARD IS HIDDEN"
    VISIBLE "DO YOU WANT TO HIT OR STAND? (H/S)"
    GIMMEH HIT_STAND
    BOTH SAEM HIT_STAND AN "H"
    O RLY?
        YA RLY
            I IZ MANYHANDS MKAY
        NO WAI 
            VISIBLE "BYE BYE"
    OIC
IF U SAY SO


HOW IZ I MANYHANDS
    VISIBLE "HI"

IF U SAY SO

VISIBLE "HAI!! WELCOME TO BLACKJACK!!!"
VISIBLE "THE DEALER DOES NOT HIT ON A SOFT 17"
VISIBLE "POINTS : 100"

I HAS A PLAYER_POINTS ITZ 100
I HAS A CHOICE
I HAS A HIT_STAND

GIMMEH CHOICE

BOTH SAEM CHOICE AN "Y"
O RLY?
    YA RLY
        VISIBLE "LETS PLAY"
        I IZ FIRSTHAND MKAY
    NO WAI
        VISIBLE "BYE BYE"
OIC


KTHXBYE