HAI 1.4

OBTW
   CREATES A DECK OF 52 CARDS USING RANKS AND SUITS
TLDR

HOW IZ I MAKEDECK
   I HAS A DECK ITZ A BUKKIT

   BTW RANKS
   I HAS A RANKS ITZ A BUKKIT
   RANKS HAS A SRS 0 ITZ "A"
   RANKS HAS A SRS 1 ITZ "2"
   RANKS HAS A SRS 2 ITZ "3"
   RANKS HAS A SRS 3 ITZ "4"
   RANKS HAS A SRS 4 ITZ "5"
   RANKS HAS A SRS 5 ITZ "6"
   RANKS HAS A SRS 6 ITZ "7"
   RANKS HAS A SRS 7 ITZ "8"
   RANKS HAS A SRS 8 ITZ "9"
   RANKS HAS A SRS 9 ITZ "10"
   RANKS HAS A SRS 10 ITZ "J"
   RANKS HAS A SRS 11 ITZ "Q"
   RANKS HAS A SRS 12 ITZ "K"

   BTW SUITS
   I HAS A SUITS ITZ A BUKKIT
   SUITS HAS A SRS 0 ITZ "Spades"
   SUITS HAS A SRS 1 ITZ "Hearts"
   SUITS HAS A SRS 2 ITZ "Clubs"
   SUITS HAS A SRS 3 ITZ "Diamonds"

   I HAS A INDEX ITZ 0

   IM IN YR SUITLOOP UPPIN YR SIDX TIL BOTH SAEM SIDX 4
      IM IN YR RANKLOOP UPPIN YR RIDX TIL BOTH SAEM RIDX 13
         I HAS A CARD
         CARD R SMOOSH RANKS'Z SRS RIDX AN " of " AN SUITS'Z SRS SIDX MKAY
         DECK HAS A SRS INDEX ITZ CARD
         INDEX R SUM OF INDEX AN 1
      IM OUTTA YR RANKLOOP
   IM OUTTA YR SUITLOOP

   FOUND YR DECK
IF U SAY SO


BTW MAKE DECK
I HAS A DECK ITZ A BUKKIT
DECK R I IZ MAKEDECK MKAY

BTW PRINT DECK
IM IN YR LOOP UPPIN YR INDEX TIL BOTH SAEM INDEX 52
   VISIBLE DECK'Z SRS INDEX
IM OUTTA YR LOOP

KTHXBYE